# Generated by Django 3.0.2 on 2020-04-28 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userAlias', models.CharField(max_length=20, unique=True)),
                ('userPwd', models.CharField(default='66666666', max_length=20)),
                ('userGender', models.BooleanField(default=True)),
                ('userAvatar', models.FilePathField(path='Avatar/')),
                ('user123', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False)),
                ('messageType', models.NullBooleanField(default=True)),
                ('messageCx', models.IntegerField(default=0)),
                ('messageCy', models.IntegerField(default=0)),
                ('messageText', models.CharField(default='我不想上学QAQ', max_length=144)),
                ('messageVoice', models.FileField(unique=True, upload_to='Voice/')),
                ('likeCount', models.IntegerField(default=0)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artalk_base.user')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cmoold', models.AutoField(primary_key=True, serialize=False)),
                ('cmContent', models.CharField(default='我不想上学！（破音）', max_length=144)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='artalk_base.user')),
            ],
        ),
    ]
