# Generated by Django 3.0.2 on 2020-04-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user123',
        ),
        migrations.AddField(
            model_name='user',
            name='userMobile',
            field=models.CharField(default='13713800000', max_length=12),
        ),
    ]
