# Generated by Django 3.0.2 on 2020-04-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0002_auto_20200428_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='userMobile',
            new_name='userPhone',
        ),
    ]
