# Generated by Django 3.0.2 on 2020-04-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0003_auto_20200428_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userAvatar',
            field=models.FilePathField(path='Avatar/', unique=True),
        ),
    ]
