# Generated by Django 3.0.2 on 2020-04-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0004_auto_20200428_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageVoice',
            field=models.FilePathField(path='Voice/', unique=True),
        ),
    ]
