# Generated by Django 3.0.2 on 2020-04-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0005_auto_20200428_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='userId',
            new_name='usrID',
        ),
    ]
