# Generated by Django 3.0.2 on 2020-04-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0007_auto_20200428_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmoold',
            new_name='cmId',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='cmContent',
            new_name='cmText',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='likeCount',
            new_name='msCmCount',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageCx',
            new_name='msCx',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageCy',
            new_name='msCy',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageId',
            new_name='msId',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='userID',
            new_name='msLikeCount',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageText',
            new_name='msText',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageType',
            new_name='msType',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='messageVoice',
            new_name='msVoice',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userId',
        ),
        migrations.AddField(
            model_name='comment',
            name='cmMsId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmUserId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='like',
            name='likeMsId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='like',
            name='likeUserId',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='message',
            name='msUserID',
            field=models.IntegerField(default=0),
        ),
    ]
