# Generated by Django 3.0.2 on 2020-04-28 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0008_auto_20200428_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmMsId',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmText',
            field=models.CharField(default='志之所趋 无远弗届', max_length=144),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmUserId',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeMsId',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeUserId',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='message',
            name='msCmCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='msCx',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='msCy',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='msLikeCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='msUserID',
            field=models.CharField(max_length=6),
        ),
    ]
