# Generated by Django 3.0.2 on 2020-04-29 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0009_auto_20200428_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='msType',
        ),
    ]
