# Generated by Django 3.0.2 on 2020-04-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0010_remove_message_mstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msVoice',
            field=models.FilePathField(blank=True, null=True, path='Voice/'),
        ),
    ]
