# Generated by Django 3.0.2 on 2020-04-30 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0011_auto_20200430_2023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='like',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msLikeCount',
        ),
        migrations.AddField(
            model_name='comment',
            name='cmUserDisLikeID',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='cmUserLikeID',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msUserDisLikeID',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='msUserLikeID',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msText',
            field=models.CharField(blank=True, max_length=144, null=True),
        ),
    ]
