# Generated by Django 3.0.2 on 2020-04-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0012_auto_20200430_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('disLikeId', models.AutoField(primary_key=True, serialize=False)),
                ('disLikeUserId', models.CharField(max_length=6)),
                ('disLikeMsId', models.CharField(max_length=6)),
                ('disLikeCmId', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False)),
                ('likeUserId', models.CharField(max_length=6)),
                ('likeMsId', models.CharField(max_length=6)),
                ('likeCmId', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cmUserDisLikeID',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='cmUserLikeID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msUserDisLikeID',
        ),
        migrations.RemoveField(
            model_name='message',
            name='msUserLikeID',
        ),
        migrations.AddField(
            model_name='comment',
            name='msUserDisLikeCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='msUserLikeCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='msUserDisLikeCount',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='msUserLikeCount',
            field=models.SmallIntegerField(default=0),
        ),
    ]
