# Generated by Django 3.0.2 on 2020-04-30 22:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0015_auto_20200430_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 38, 15, 631989)),
        ),
        migrations.AddField(
            model_name='dislike',
            name='disLikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 38, 15, 631989)),
        ),
        migrations.AddField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 38, 15, 630934)),
        ),
    ]
