# Generated by Django 3.0.2 on 2020-04-30 22:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0016_auto_20200430_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 40, 47, 598855)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 40, 47, 599852)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='disLikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 40, 47, 598855)),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 22, 40, 47, 598855)),
        ),
    ]
