# Generated by Django 3.0.2 on 2020-04-30 23:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artalk_base', '0017_auto_20200430_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 52, 53, 681004)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='disLikeCmId',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='disLikeMsId',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='disLikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 52, 53, 679949)),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeCmId',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeMsId',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 52, 53, 679949)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 30, 23, 52, 53, 679949)),
        ),
    ]
