# Generated by Django 3.0.2 on 2020-05-19 11:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('cmId', models.AutoField(primary_key=True, serialize=False)),
                ('cmText', models.CharField(default='身体是革命的本钱', max_length=144)),
                ('cmUserId', models.CharField(max_length=6)),
                ('cmVId', models.CharField(max_length=6)),
                ('cmLikeCount', models.SmallIntegerField(default=0)),
                ('cmDisLikeCount', models.SmallIntegerField(default=0)),
                ('cmTime', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 12, 13, 165412))),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('DislikeId', models.AutoField(primary_key=True, serialize=False)),
                ('DislikeUserId', models.CharField(max_length=6)),
                ('DislikeVId', models.CharField(max_length=6, null=True)),
                ('DislikeCmId', models.CharField(max_length=6, null=True)),
                ('DislikeTime', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 12, 13, 164415))),
            ],
        ),
        migrations.CreateModel(
            name='like',
            fields=[
                ('likeId', models.AutoField(primary_key=True, serialize=False)),
                ('likeUserId', models.CharField(max_length=6)),
                ('likeVId', models.CharField(max_length=6, null=True)),
                ('likeCmId', models.CharField(max_length=6, null=True)),
                ('likeTime', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 12, 13, 164415))),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userAlias', models.CharField(max_length=20, unique=True)),
                ('userPwd', models.CharField(default='66666666', max_length=20)),
                ('userTime', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 12, 13, 164415))),
                ('userPhone', models.CharField(default='13713800000', max_length=12)),
                ('userGender', models.BooleanField(default=True)),
                ('userAvatar', models.FilePathField(path='Edot/avatar/', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='video',
            fields=[
                ('videoId', models.AutoField(primary_key=True, serialize=False)),
                ('videoTitle', models.CharField(max_length=20, unique=True)),
                ('videoInfo', models.CharField(default='这个Up很懒，没有写简介', max_length=200)),
                ('videoSrc', models.FilePathField(path='Edot/video', unique=True)),
                ('videoCover', models.FilePathField(path='Edot/cover', unique=True)),
                ('videoViews', models.IntegerField(default=0)),
                ('videoLikes', models.IntegerField(default=0)),
                ('videoDisLikes', models.IntegerField(default=0)),
                ('videoComments', models.IntegerField(default=0)),
                ('videoTime', models.DateTimeField(default=datetime.datetime(2020, 5, 19, 11, 12, 13, 163417))),
                ('videoDuration', models.IntegerField(default=60)),
                ('videoUserId', models.CharField(max_length=6)),
                ('videoLocation', models.SmallIntegerField(default=0)),
                ('videoGoal', models.SmallIntegerField(default=0)),
                ('videoMusucle', models.SmallIntegerField(default=0)),
                ('videoDifficulty', models.SmallIntegerField(default=0)),
                ('videoTool', models.SmallIntegerField(default=0)),
            ],
        ),
    ]
