# Generated by Django 3.0.2 on 2020-05-19 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edotBackend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 0, 9, 395731)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='DislikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 0, 9, 394736)),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 0, 9, 394736)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 0, 9, 394736)),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 12, 0, 9, 394061)),
        ),
    ]
