# Generated by Django 3.0.2 on 2020-05-19 21:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edotBackend', '0002_auto_20200519_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 18, 6, 246395)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='DislikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 18, 6, 246395)),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 18, 6, 245363)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 18, 6, 245363)),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 19, 21, 18, 6, 245363)),
        ),
    ]
