# Generated by Django 3.1 on 2020-05-20 01:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edotBackend', '0011_auto_20200520_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='cmTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 1, 3, 31, 365453)),
        ),
        migrations.AlterField(
            model_name='dislike',
            name='disLikeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 1, 3, 31, 365060)),
        ),
        migrations.AlterField(
            model_name='like',
            name='likeTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 1, 3, 31, 364681)),
        ),
        migrations.AlterField(
            model_name='user',
            name='userTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 1, 3, 31, 364189)),
        ),
        migrations.AlterField(
            model_name='video',
            name='videoTime',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 20, 1, 3, 31, 363536)),
        ),
    ]
